#pragma config(Sensor, in1,    leftLF,         sensorLineFollower)//sets in1 as left line follower
#pragma config(Sensor, in2,    centerLF,       sensorLineFollower)//sets in2 as center line follower
#pragma config(Sensor, in3,    rightLF,        sensorLineFollower)//sets in3 as right line follower
#pragma config(Sensor, dgtl3,  bumpSwitch,     sensorTouch)//sets dgtl3 as bump switch
#pragma config(Sensor, dgtl4,  LE,             sensorQuadEncoder)//sets dgtl4 as left encoder
#pragma config(Sensor, dgtl6,  RE,             sensorQuadEncoder)//sets dgtl as right encoder
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)//sets dgtl12 as green
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)//sets port2 as right motor, reversed
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)//sets port 3 as left motor
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//to separate
int threshhold; //starts threshhold variable
int turnstop;	//starts turnstop variable
void farleft ();	//starts farleft variable
void farright ();	//starts farright variable
void center ();	//starts center variable
void halfleft ();	//starts halfleft variable
void allstop ();	//starts allstop variable
void halfright();	//starts halfright variable
void nothing();	//starts off the line variable
//to separate
task main()	//starts task main
{	//starts task main
	threshhold=(SensorValue(centerLF)+SensorValue(rightLF))/2;	//sets the threhhold for where it is
	turnstop=0;	//turns turnstop to 0
	while(1==1)//starts loop
	{//opens loop
		SensorValue(RE)=0;//sets right encoder at 0
		SensorValue(LE)=0;//sets leftencoder at 0
		motor[rightMotor] = (vexRT[Ch2]);	//control for right side
		motor[leftMotor] = (vexRT[Ch3]);	//control for left side
		while(vexRT[Btn6U]==1)	//turns it into autonomous
		{//starts autonomous loop
			if ((SensorValue(leftLF)>threshhold)&&(SensorValue(centerLF)<threshhold))	//if it is on the far left
			{// opens loop
				if(SensorValue(LE)-SensorValue(RE)>=500)//if it stopped at the end of the line
				{// opens loop
					stopMotor(leftMotor);//stops left motor
					stopMotor(rightMotor);//stops right motor
					untilTouch(bumpSwitch);//waits for button  press
				}//closes loop
				farleft ();//starts countersteering
				SensorValue(RE)=0;//sets right encoder at 0
				SensorValue(LE)=0;//sets left encoder at 0
			}//closes loop
			if((SensorValue(rightLF)>threshhold)&&(SensorValue(centerLF)<threshhold))	//if it is on the far right
			{// opens loop
				if(SensorValue(LE)-SensorValue(RE)>=500)//if it stopped at the end of the line
				{// opens loop
					stopMotor(leftMotor);//stops left motor
					stopMotor(rightMotor);//stops right motor
					untilTouch(bumpSwitch);//waits for button  press
				}//closes loop
				farright ();//starts countersteering
				SensorValue(RE)=0;//sets right encoder at 0
				SensorValue(LE)=0;//sets left encoder at 0
			}//closes loop
			if((SensorValue(centerLF)>threshhold)&&(SensorValue(leftLF)<threshhold)+(SensorValue(rightLF)<threshhold))	// if it is on the line
			{// opens loop
				if(SensorValue(LE)-SensorValue(RE)>=500)//if it stopped at the end of the line
				{// opens loop
					stopMotor(leftMotor);//stops left motor
					stopMotor(rightMotor);//stops right motor
					untilTouch(bumpSwitch);//waits for button  press
				}//closes loop
				center ();//moves it forward
				SensorValue(RE)=0;//sets right encoder at 0
				SensorValue(LE)=0;//sets left encoder at 0
			}//closes loop
			if((SensorValue(leftLF)>threshhold)&&(SensorValue(centerLF)>threshhold))	//if it is half left
			{// opens loop
				if(SensorValue(LE)-SensorValue(RE)>=500)//if it stopped at the end of the line
				{// opens loop
					stopMotor(leftMotor);//stops left motor
					stopMotor(rightMotor);//stops right motor
					untilTouch(bumpSwitch);//waits for button  press
				}//closes loop
				halfleft ();//starts countersteering
				SensorValue(RE)=0;//sets right encoder at 0
				SensorValue(LE)=0;//sets left encoder at 0
			}//closes loop
			if((SensorValue(leftLF)>threshhold)&&(SensorValue(centerLF)>threshhold)&&(SensorValue(rightLF)>threshhold))//when it gets to the stop
			{// opens loop
				if(SensorValue(LE)-SensorValue(RE)>=500)//if it stopped at the end of the line
				{// opens loop
					stopMotor(leftMotor);//stops left motor
					stopMotor(rightMotor);//stops right motor
					untilTouch(bumpSwitch);//waits for button  press
				}//closes loop
				allstop ();//starts countersteering
				SensorValue(RE)=0;//sets right encoder at 0
				SensorValue(LE)=0;//sets left encoder at 0
			}//closes loop
			if((SensorValue(rightLF)>threshhold)&&(SensorValue(centerLF)>threshhold))//if it is half right
			{// opens loop
				if(SensorValue(LE)-SensorValue(RE)>=500)//if it stopped at the end of the line
				{// opens loop
					stopMotor(leftMotor);//stops left motor
					stopMotor(rightMotor);//stops right motor
					untilTouch(bumpSwitch);//waits for button  press
				}//closes loop
				halfright();//starts countersteering
				SensorValue(RE)=0;//sets right encoder at 0
				SensorValue(LE)=0;//sets left encoder at 0
			}//closes loop
			if((SensorValue(leftLF)<threshhold)&&(SensorValue(centerLF)<threshhold)&&(SensorValue(rightLF)<threshhold))//when it is off the line
			{// opens loop
				nothing();//starts countersteering
			}//closes loop
		}//closes loop
	}//closes loop
}//closes loop
//to separate
void farleft()//void program
{// opens loop
	startMotor(rightMotor, 30);//starts right motor at 30
	startMotor(leftMotor, -30);//starts left motor at -30
}//closes loop
void farright()//void program
{// opens loop
	startMotor(rightMotor, -30);//starts right motor at -30
	startMotor(leftMotor, 30);//starts left motor at 30
}//closes loop
void center()//void program
{// opens loop
	startMotor(rightMotor, 30);//starts right motor at 30
	startMotor(leftMotor, 30);//starts left motor at 30
}//closes loop
void halfleft ()//void program
{// opens loop
	startMotor(leftMotor, -30);//starts left motor at -30
	startMotor(rightMotor, 30);//starts right motor at 30
}//closes loop
void halfright ()//void program
{// opens loop
	startMotor(rightMotor, -30);//starts right motor at -30
	startMotor(leftMotor, 30);//starts left motor at 30
}//closes loop
void allstop ()//void program
{// opens loop
	stopMotor(rightMotor);//stops right motor
	stopMotor(leftMotor);//stops left motor
	turnLEDOn(green);//turns on LED
	wait(6);//waits for 6 seconds
	turnLEDOff(green);//turns off LED
	waitInMilliseconds(500);//truns led off for half a second
	startMotor(rightMotor,30);//starts right motor at 30
	startMotor(leftMotor,30);//starts left motor at 30
	waitInMilliseconds(300);//waits for robot to stop
}//closes loop
void nothing ()//void program
{// opens loop
	startMotor(rightMotor,30);//starts right motor at 30
	startMotor(leftMotor,-30);//starts left motor at -30
}//closes loop
