#pragma config(Sensor, in1,    leftLF,         sensorLineFollower)
#pragma config(Sensor, in2,    centerLF,       sensorLineFollower)
#pragma config(Sensor, in3,    rightLF,        sensorLineFollower)
#pragma config(Sensor, dgtl3,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl4,  LE,             sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  RE,             sensorQuadEncoder)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshhold;
int turnstop;
void farleft ();
void farright ();
void center ();
void halfleft ();
void allstop ();
void halfright();
void nothing();
task main()
{
	threshhold=(SensorValue(centerLF)+SensorValue(rightLF))/2;
	turnstop=0;
	untilTouch(bumpSwitch);
	wait(.5);
	SensorValue(RE)=0;
	SensorValue(LE)=0;
	while(1==1)
	{

		if ((SensorValue(leftLF)>threshhold)&&(SensorValue(centerLF)<threshhold))  //if the linefollowers see the line all thge way on the left
		{
			if(SensorValue(LE)-SensorValue(RE)>=500)
			{
				stopMotor(leftMotor);
				stopMotor(rightMotor);
				untilTouch(bumpSwitch);
			}
			farleft ();
			SensorValue(RE)=0;
			SensorValue(LE)=0;
		}
		if((SensorValue(rightLF)>threshhold)&&(SensorValue(centerLF)<threshhold))  //if the line followers see the line all the way to the right
		{
			if(SensorValue(LE)-SensorValue(RE)>=500)
			{
				stopMotor(leftMotor);
				stopMotor(rightMotor);
				untilTouch(bumpSwitch);
			}
			farright ();
			SensorValue(RE)=0;
			SensorValue(LE)=0;
		}
		if((SensorValue(centerLF)>threshhold)&&(SensorValue(leftLF)<threshhold)+(SensorValue(rightLF)<threshhold))  // if the car is on the line
		{
			if(SensorValue(LE)-SensorValue(RE)>=500)
			{
				stopMotor(leftMotor);
				stopMotor(rightMotor);
				untilTouch(bumpSwitch);
			}
			center ();
			SensorValue(RE)=0;
			SensorValue(LE)=0;
		}
		if((SensorValue(leftLF)>threshhold)&&(SensorValue(centerLF)>threshhold)) // if it is half to the left
		{
			if(SensorValue(LE)-SensorValue(RE)>=500)
			{
				stopMotor(leftMotor);
				stopMotor(rightMotor);
				untilTouch(bumpSwitch);
			}
			halfleft ();
			SensorValue(RE)=0;
			SensorValue(LE)=0;
		}
		if((SensorValue(leftLF)>threshhold)&&(SensorValue(centerLF)>threshhold)&&(SensorValue(rightLF)>threshhold)) // used to stop on the perpendicular line
		{
			if(SensorValue(LE)-SensorValue(RE)>=500)
			{
				stopMotor(leftMotor);
				stopMotor(rightMotor);
				untilTouch(bumpSwitch);
			}
			allstop ();
			SensorValue(RE)=0;
			SensorValue(LE)=0;
		}
		if((SensorValue(rightLF)>threshhold)&&(SensorValue(centerLF)>threshhold))// if the line is half on the right
		{
			if(SensorValue(LE)-SensorValue(RE)>=500)
			{
				stopMotor(leftMotor);
				stopMotor(rightMotor);
				untilTouch(bumpSwitch);
			}
			halfright();
			SensorValue(RE)=0;
			SensorValue(LE)=0;
		}
		if((SensorValue(leftLF)<threshhold)&&(SensorValue(centerLF)<threshhold)&&(SensorValue(rightLF)<threshhold))// if there is no line to be found
		{
			nothing();
		}
	}
}
void farleft()
{
	startMotor(rightMotor, 30);
	startMotor(leftMotor, -30);
}
void farright()
{
	startMotor(rightMotor, -30);
	startMotor(leftMotor, 30);
}
void center()
{

	startMotor(rightMotor, 30);
	startMotor(leftMotor, 30);
}
void halfleft ()
{

	startMotor(leftMotor, -30);
	startMotor(rightMotor, 30);
}

void halfright ()
{

	startMotor(rightMotor, -30);
	startMotor(leftMotor, 30);
}
void allstop ()
{
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	turnLEDOn(green);
	wait(6);
	turnLEDOff(green);
	waitInMilliseconds(500);
	startMotor(rightMotor,30);
	startMotor(leftMotor,30);
	waitInMilliseconds(300);
}
void nothing ()
{
	startMotor(rightMotor,30);
	startMotor(leftMotor,-30);

}
